fetch and export image digest

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -83,6 +83,7 @@ dockerfile=${BUILDKITE_PLUGIN_DOCKER_BUILD_DOCKERFILE:-Dockerfile}
 context=${BUILDKITE_PLUGIN_DOCKER_BUILD_CONTEXT:-.}
 push=${BUILDKITE_PLUGIN_DOCKER_BUILD_PUSH:-false}
 secret_file=${BUILDKITE_PLUGIN_DOCKER_BUILD_SECRET_FILE:-}
+getdigest=${BUILDKITE_PLUGIN_DOCKER_BUILD_GET_DIGEST:-false}
 
 tagsflags=()
 
@@ -171,6 +172,35 @@ if [[ $status -eq 0 ]] ; then
   display_success "Docker build succeeded"
 else
   fail_with_message "Docker build failed"
+fi
+
+if [[ "${getdigest}" == "true" ]] ; then
+  echo "Exporting image digest"
+
+  # Export image digest
+  first_tag=""
+  for item in "${tagsflags[@]}"; do
+    if [[ "$item" != "--tag" ]]; then
+      first_tag="$item"
+      break
+    fi
+  done
+
+  if [[ -n "$first_tag" ]]; then
+    image_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "$first_tag")
+    if [[ -n "$image_digest" ]]; then
+      echo "Image Digest: $image_digest"
+      buildkite-agent meta-data set "docker-image-digest" "$image_digest"
+      export DBBP_IMAGE_DIGEST="$image_digest"
+      echo "Digest has been stored in DBBP_IMAGE_DIGEST environment variable"
+      echo "Digest has been stored as buildkite meta-data with key 'docker-image-digest'"
+      display_success "Image digest exported: \`${image_digest}\`"
+    else
+      echo "⚠️ Could not determine image digest for tag \`${first_tag}\`" >&2
+    fi
+  else
+    echo "⚠️ Could not determine the first tag to inspect for image digest." >&2
+  fi
 fi
 
 # Push
